### ISSUE TITLE
Where are the binaries?

### ISSUE THREAD

**Issue by burzum** [Anrop/AAR-Addon#30]
You write here https://forums.bistudio.com/topic/175173-web-json-pusher-winlinux-library/ that the binaries can be found here in the repository as well, but either they're not there or I'm not finding them?

I don't want to install docker again, it was a pain on windows, to compile this. So it would be awesome if we could just get a binary for download.

I couldn't test it yet but this addon looks awesome if it works, nice work! 👍

**Comment by Dahlgren** [comment]
Hi!

Binaries are no longer kept in the repo. The older ones can be found in the original extension writers repo, https://github.com/martinengstrom/Arma-Stats-Track-Addon/tree/master/bin.

Once this is considered mature enough binaries will be available with each tagged release. I might be able to compile one for you, did you setup the Rails API which is required for storing the missions data?

We've been using it for the last 6 months with great success. The web frontend with our "recent" missions can be seen at https://aar.anrop.se/

**Comment by burzum** [comment]
Hi Dahlgren, thanks for the quick reply!

I'm not planing on using  Rails, but if you check my Github Profile you'll see that I'm pretty much involved with CakePHP. :) CakePHP, at least the older versions, were very similar to RoR. I don't know if 3.x is still sharing a lot similarity.

The idea is to release a CakePHP plugin for your addon. I just need to get it to work first. Writing that plugin should be just a matter of a few hours.

Maybe you could support Vagrant besides Docker as well? Docker was a pain in the ass for me when we've tried to use it in our company. Vagrant is bigger but works very well for me.

I can use the old binaries but if you could compile a set of new binaries it would be awesome.

**Comment by Dahlgren** [comment]
Here's a somewhat up to date API specification for all requests and models. The GET requests should be about the same but in reverse.

[AAR API.pdf](https://github.com/Anrop/AAR-Addon/files/469502/AAR.API.pdf)

**Comment by burzum** [comment]
Thank you! Do you have an ETA on the tagged release?

**Comment by Dahlgren** [comment]
No ETA for a tagged release. Do you have an endpoint I could compile a binary for you? It's also possible to override the endpoint using a userconfig but that requires file patching in Arma to be enabled.

**Comment by Dahlgren** [comment]
Binaries can be found on [Steam Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1968550292)
