### ISSUE TITLE
Markers are misaligned

### ISSUE THREAD

**Issue by Frozen-byte** [Anrop/AAR-Addon#51]
All Markers seem shifted to the Northwest.
Any Idea how this could happen?

Example:
https://aar.byte.pm/missions/28  
https://aar.byte.pm/missions/44

**Comment by Dahlgren** [comment]
The Anrop map tiles CDN has been changed into a new format. The public AAR Frontend is currently not fully compatible with maps which sides are not a power of two.

**Comment by Frozen-byte** [comment]
Okay, your Fix in https://github.com/Dahlgren/AAR-Frontend/commit/a947b5f4987818a45ae7f916a5209d97bc08ca2c worked very well, thank you!
