### ISSUE TITLE
Submarines are invisible

### ISSUE THREAD

**Issue by Frozen-byte** [Anrop/AAR-Addon#65]
Have a look at https://aar.byte.pm/missions/69 timestamp `1h 17m 47s` northern island player *Wookie* just disappears, as he enters the submarine.

**Comment by Dahlgren** [comment]
Units inside vehicles are hidden from rendering in the frontend

**Comment by Dahlgren** [comment]
Marker class for simulation type submarine is missing in frontend, https://github.com/Anrop/AAR-Frontend/issues/148
